# Generated by Django 4.2.7 on 2024-02-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package_delete_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
